// Phase 1 UI Language - Official labels, buttons, and text
// Collaboration-first, action-oriented, plural and relational language
export const UILanguage = {
  profile: {
    howIWork: "How I work",
    builtWithOthers: "What I've built with others",
    futureProjectIdeas: "Future project ideas",
    about: "About",
  },
  collabCircle: {
    title: "People I've built with",
    confirmCollaboration: "Confirm collaboration",
    lockCollaboration: "Lock collaboration",
    contributionSummary: "Contribution summary",
    emptyState: "No collaborations logged yet",
    emptyStateTip: "Confirm collaborations to build your network",
  },
  projectHub: {
    startCollaboration: "Start a collaboration",
    joinCollaboration: "Join this collaboration",
    signalIntent: "Signal intent to participate",
    collaborators: "Collaborators",
    emptyState: "No active collaborations yet",
  },
  coalitions: {
    seeProjects: (name) => `See projects in ${name}`,
    browseCollaborators: (name) => `Browse collaborators in ${name}`,
  },
  communities: {
    join: (name) => `Join ${name}`,
    comment: (name) => `Comment in ${name}`,
  },
  vcl: {
    contributionSummary: "Contribution summary",
    roleAndInput: "Role & input",
    confirmedByCollaborators: "Confirmed by collaborators",
    readyForReuse: "Ready for reuse",
    pageTitle: "Collaborations",
    pageDescription: "Log and confirm collaborations to build your network",
    pendingTitle: "Pending confirmation",
    confirmedTitle: "Confirmed collaborations",
    waitingMessage: "Waiting for mutual confirmation",
    confirmedLabel: "Confirmed",
    lockedLabel: "Locked",
  },
  emptyStates: {
    noCollaborations: "Log your first collaboration",
    collaborationsReusable: "Confirm collaborations to build your network",
    noProjects: "Start a collaboration to begin",
    noUsers: "Find people to build with",
    noProjectsFound: "Find collaborations to join",
    noCoalitions: "Browse coalitions to discover teams",
  },
  general: {
    collabCircle: "Collab Circle",
    workBuiltTogether: "Work built together",
    peopleBuiltWith: "People I've built with",
    discover: "Discover",
    hub: "Hub",
    profile: "Profile",
  },
  status: {
    pending: "Pending",
    confirmed: "Confirmed",
    locked: "Locked",
    open: "Open",
    inProgress: "In progress",
    completed: "Completed",
  },
  actions: {
    confirmCollaboration: "Confirm collaboration",
    lockCollaboration: "Lock this collaboration",
    reconnect: "Re-connect",
    startCollaboration: "Start a collaboration",
    joinCollaboration: "Join this collaboration",
    signalIntent: "Signal intent to participate",
    logCollaboration: "Log collaboration",
    startProgress: "Start working",
    complete: "Complete",
    cancel: "Cancel",
    delete: "Remove",
  },
  forms: {
    email: "Email",
    password: "Password",
    username: "Username",
    title: "Title",
    objective: "Objective",
    projectType: "Project Type",
    neededArchetypes: "Needed Archetypes",
    openRoles: "Open Roles",
    timeline: "Timeline",
    region: "Region",
    coalitionTags: "Coalition Tags",
    collaboratorUsername: "Collaborator Username",
    contributionSummary: "Contribution summary",
  },
  messages: {
    loginFailed: "Login failed",
    signupFailed: "Signup failed",
    loading: "Loading...",
    notFound: "Not found",
    error: "Something went wrong",
    confirmDelete: "Remove this collaboration?",
  },
};

